source 'https://github.com/CocoaPods/Specs.git'

target 'EmojiKit', :exclusive => true do
  pod "EmojiKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "EmojiKit", :path => "../"

  
end
